FeaturesAdd Navbar + Headlines
ichala/Portfolio pull request #2
Opened 2022-03-16 18:58 UTC by ichala

Add Navbar Add Header Add style Install linters

2022-03-16 20:31 UTC, mahbubul14 requested changes
Hi @ichala ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [x] Please use [CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries.asp) for your mobile version. It is not currently optimized properly for the mobile version.

- [x] Check the comments under the review for more suggestions. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.

### Optional suggestions

- [ ] For readability, please add two spaces of indentation. Do not use the tab key. You did it throughout your code in the `HTML` file. Please fix it. [For the HTML & CSS best practices ](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)we should follow the rules.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-16 20:31 UTC, mahbubul14 commented on index.html
> +    </section>
- [x] Please use a `header` tag instead of `section` tag. :writing_hand:  

- [x] Your design currently doesn't match with Figma design. Kindly add some space on both right and left sides.

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![w2](https://user-images.githubusercontent.com/70483835/158681699-0db18abc-0576-4f28-9100-20b8c1ed4c44.png) | ![w1](https://user-images.githubusercontent.com/70483835/158680670-75226c4f-e85b-4f57-aed8-179d3d599de6.png)

2022-03-16 20:31 UTC, mahbubul14 commented on index.html
> +            <img class="tool-button" src="images/Enabled.png" alt="toolimage">
- [x] The hamburger button on the right should have a `nav` tag. Please work on that. :writing_hand:

2022-03-16 20:31 UTC, mahbubul14 commented on index.html
> +</div>
- [ ] Instead of `div` tag please use `ul` tag and `a` tag should be inside of `li` tag. :writing_hand:

2022-03-17 08:59 UTC, ShoiraTa commented
## **STATUS: APPROVED  🟢 ** 
------
### Hi @ichala , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 09:01 UTC, merged