Work & About me Sections
ichala/Portfolio pull request #3
Opened 2022-03-17 13:01 UTC by ichala

Add my works section 
Add about me section
Add stylelint file to test locally

2022-03-17 14:04 UTC, Kingstalux requested changes
Hi @ichala , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966](https://user-images.githubusercontent.com/85113567/158824980-ccd15e5e-535f-40dc-ad4d-28a6416fcb12.gif)


## Highlights
✅ Linters are passing
✅ Good pull request description
✅ Good commit messages 🔥 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 14:04 UTC, Kingstalux commented on index.html
> +      <h1 class="primary-text">My Recent<br> Works</h1>
- [x] Good job so far 👍 For best semantic practices, your site should have only one main `h1` tag. As a result, kindly make this into an `h2` or `h3` tag.

2022-03-17 14:04 UTC, Kingstalux commented on index.html
> +          </div>
- [x] Good job applying the project card image 💯 but it would be great to follow the template design and your project images have some extra writings on them. Kindly fix this issue.
- [x] Also kindly align your project cards to the center of your page. Right now, the are leaning towards the right side 😄 
- Your design:
![Annotation 2022-03-17 142908](https://user-images.githubusercontent.com/85113567/158821909-dc0bfd4d-f68c-4996-a631-3b91f80cf089.jpg)
- Figma design:
![Annotation 2022-03-17 142924](https://user-images.githubusercontent.com/85113567/158821943-efb9cad5-f34e-4091-9253-eb7f430d771f.jpg)

2022-03-17 14:04 UTC, Kingstalux commented on index.html
> +            </div>
- [x] Since this is the title of your project card, it would be better to use an `hx` tag like an `h2` or `h3` tag here. Kindly rectify this in all your project cards 👍

2022-03-17 14:04 UTC, Kingstalux commented on index.html
> +              <button class="">See Project</button>
- [x] Kindly implement the correct button interactions. Right when I hover on your button, a shadow appears. Kindly remove that extra style and follow the template design
- button interactions:
![Annotation 2022-03-17 145114](https://user-images.githubusercontent.com/85113567/158823503-009e12ef-b8e8-4c80-8f20-e186138a310e.jpg)

2022-03-17 14:04 UTC, Kingstalux commented on index.html
> +        <h1 class="primary-text">About me</h1>
- [x] Kindly make this into a `h2` tag as your page already has a main `h1` heading tag. This is for best semantic practices 👍 
- [x] Also this section is missing a background image at the top. It would be best to add that too so as to follow the template design.
- Your design:
![Annotation 2022-03-17 143004](https://user-images.githubusercontent.com/85113567/158824063-b4a08043-fd45-4b32-b413-3eef87d36bcc.jpg)
- Figma design:
![Annotation 2022-03-17 143016](https://user-images.githubusercontent.com/85113567/158824110-9c2e307c-e185-44b7-9de7-197d5b9b16b4.jpg)

2022-03-17 14:04 UTC, Kingstalux commented on index.html
> +            Html
- [x] Good job placing your elements in this section in a list 💯 It would be great if you could follow the right alignment for each of the technology categories and also try to center your cards on your page so as to follow the template design.
- Your design:
![Annotation 2022-03-17 143118](https://user-images.githubusercontent.com/85113567/158824732-04af93ca-3a98-4aa0-b085-3e1b3ad14c02.jpg)
- Figma design:
![Annotation 2022-03-17 143139](https://user-images.githubusercontent.com/85113567/158824773-ddb0ce52-008d-4650-9d0f-eb773c9d0561.jpg)

2022-03-17 15:20 UTC, ichala commented on index.html
> +        <h1 class="primary-text">About me</h1>
![screen_shot](https://user-images.githubusercontent.com/89282221/158833677-8b9afae2-5844-46e0-b5b0-a018ae817095.png)

Thank you, Sir, I think you have the same google chrome issue that I have please uncomment the line of codes I provided in the CSS file, I put it there because of this issue called user-agent-stylesheets... 
everything is aligned in the center its just a navigator issue

2022-03-17 15:26 UTC, ichala commented on index.html
> +            Html
@Kingstalux  **same thing here as well** 
![screen2](https://user-images.githubusercontent.com/89282221/158834175-c4aa6c5c-8974-4023-a0c1-b0bfb219ddef.png)

2022-03-18 08:37 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @ichala   , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well implemented Figma design.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-18 08:39 UTC, merged